Check my Homewrok, please
OstapGonchar/inventory-backend pull request #4
Opened 2023-05-21 08:57 UTC by SergiiBal

2023-05-22 18:30 UTC, OstapGonchar requested changes

2023-05-22 18:30 UTC, OstapGonchar commented on src/main/java/com/inventory/controllers/OfferController.java
How about unused parameters after you moved logic into service? shouldn\t something be removed?

2023-05-22 18:30 UTC, OstapGonchar commented on src/main/java/com/inventory/controllers/OfferController.java
> +       return  offerService.convertCurrency(fromCurrency, toCurrency, amount);
this method is not needed, right?

2023-05-22 18:30 UTC, OstapGonchar commented on src/main/java/com/inventory/services/OfferService.java
> +        //TODO Sergii: move to separate Service
What about unit tests? Aren't they failing now? They should be fixed.

2023-05-22 19:26 UTC, OstapGonchar commented
@Sergii, I reviewed it

2023-05-23 19:05 UTC, SergiiBal commented on src/main/java/com/inventory/controllers/OfferController.java
You are sure.. I was afraid to break something by deleting unused parameters. I will try

2023-05-25 19:30 UTC, OstapGonchar approved these changes

2023-05-25 19:30 UTC, merged